---
name: 'ot-analyze'
author: 'y3rsh'
description: 'A GitHub Action to analyze Opentrons protocols'
inputs:
  BASE_DIRECTORY:
    description: 'relative path in the repository of the root folder in which to search for to search for protocols'
    required: false
    default: 'protocols'
    type: string
runs:
  using: 'docker'
  image: 'docker://ghcr.io/y3rsh/ot-analyze:main'
branding:
  icon: 'check-square'
  color: 'white'
